version: '3'
services:

  postgres:
    build:
      context: platform/postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./${POSTGRES_STORAGE}/:/var/lib/postgresql/data

  mlflow:
    build:
      context: platform/mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    expose:
      - ${MLFLOW_EXPOSE_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./${ARTIFACTS_DIR}/:/mlflow

  jupyter_notebook:
    build:
      context: platform/notebook
      dockerfile: Dockerfile
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    depends_on:
      - mlflow
    environment:
        MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
        MLFLOW_EXPERIMENT_NAME: ${MLFLOW_EXPERIMENT_NAME}
        MLFLOW_KERAS_MODEL_LOG: ${MLFLOW_KERAS_MODEL_LOG}
        MLFLOW_KERAS_AUTO_LOG: ${MLFLOW_KERAS_AUTO_LOG}
        MLFLOW_LOG_PARAMS: ${MLFLOW_LOG_PARAMS}
        TENSORBOARD_SCALAR_LOGS: ${TENSORBOARD_SCALAR_LOGS}
        TENSORBOARD_IMAGES_DISPLAY: ${TENSORBOARD_IMAGES_DISPLAY}
        TENSORBOARD_CONFUSION_MATRIX: ${TENSORBOARD_CONFUSION_MATRIX}
        TENSORBOARD_LOGS_DIR: ${TENSORBOARD_LOGS_DIR}
    volumes:
      - ./${APP_DIR}/:${NOTEBOOK_WORKSPACE}/${APP_DIR}
      - ./${DATA_DIR}/:${NOTEBOOK_WORKSPACE}/${DATA_DIR}
      - ./${ARTIFACTS_DIR}/:/mlflow
      - ./${TENSORBOARD_LOGS_DIR}/:${NOTEBOOK_WORKSPACE}/${TENSORBOARD_LOGS_DIR}

  tensorboard:
    build:
      context: platform/tensorflow
      dockerfile: Dockerfile
    container_name: tensorboard
    volumes:
      - ./${TENSORBOARD_LOGS_DIR}/:/${TENSORBOARD_LOGS_DIR}/
    ports:
      - 6006:6006
    command: tensorboard --logdir=/${TENSORBOARD_LOGS_DIR}/